### ISSUE TITLE
android studio3.0.1 gradle4.4 下闪退

### ISSUE THREAD

**Issue by baneyue** [sensorsdata/sa-sdk-android-plugin2#2]
com.sensorsdata.analytics.android:android-gradle-plugin2:1.0.3

`02-27 10:28:44.560 16735-16735/com.yuanshi.jiaoyidashi E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: com.yuanshi.jiaoyidashi, PID: 16735
                                                                         java.lang.VerifyError: Verifier rejected class com.sensorsdata.analytics.android.runtime.FragmentAspectj: java.lang.Object com.sensorsdata.analytics.android.runtime.FragmentAspectj.ajc$inlineAccessMethod$com_sensorsdata_analytics_android_runtime_FragmentAspectj$com_sensorsdata_analytics_android_runtime_FragmentAspectj$trackFragmentView(com.sensorsdata.analytics.android.runtime.FragmentAspectj, org.aspectj.lang.ProceedingJoinPoint) failed to verify: java.lang.Object com.sensorsdata.analytics.android.runtime.FragmentAspectj.ajc$inlineAccessMethod$com_sensorsdata_analytics_android_runtime_FragmentAspectj$com_sensorsdata_analytics_android_runtime_FragmentAspectj$trackFragmentView(com.sensorsdata.analytics.android.runtime.FragmentAspectj, org.aspectj.lang.ProceedingJoinPoint): [0x0] invoke-super/virtual can't be used on private method java.lang.Object com.sensorsdata.analytics.android.runtime.FragmentAspectj.trackFragmentView(org.aspectj.lang.ProceedingJoinPoint) (declaration of 'com.sensorsdata.analytics.android.runtime.FragmentAspectj' appears in /data/app/com.yuanshi.jiaoyidashi-s_Ca2Xz4Do4Hjwy5_hAZYg==/base.apk:classes40.dex)
                                                                             at com.sensorsdata.analytics.android.runtime.FragmentAspectj.aspectOf(FragmentAspectj.java:1)
                                                                             at com.jince.home.fragment.LogoFragment.onCreateView(LogoFragment.java:84)
                                                                             at android.support.v4.app.Fragment.performCreateView(Fragment.java:2261)
                                                                             at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
                                                                             at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
                                                                             at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
                                                                             at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
                                                                             at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
                                                                             at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
                                                                             at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
                                                                             at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239)
                                                                             at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3231)
                                                                             at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3181)
                                                                             at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:192)
                                                                             at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:572)
                                                                             at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
                                                                             at com.jince.core.base.BaseFragmentActivity.onStart(BaseFragmentActivity.java:151)
                                                                             at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1339)
                                                                             at android.app.Activity.performStart(Activity.java:7385)
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3147)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3279)
                                                                             at android.app.ActivityThread.-wrap12(Unknown Source:0)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1881)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:108)
                                                                             at android.os.Looper.loop(Looper.java:166)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:7406)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:926)`

**Comment by drowtram** [comment]
我也遇到这个问题

**Comment by V-zhangyunxiang** [comment]
你好，此错误是因为 Gradle 4.4 使用了名为 D8 的新编译器，你可以在 gradle.properties 文件中包含以下内容来临时禁用 D8 并使用 DX ：
   android.enableD8=false
如果还有其它问题，也欢迎及时联系。

**Comment by imliujun** [comment]
什么时候能够支持D8？

**Comment by JJKLoGano** [comment]
D8编译器过几个月就变成默认配置了，有没有升级计划呢

**Comment by drowtram** [comment]
有没有感觉禁用D8编译器后，编译慢了好多

**Comment by wangzhzh** [comment]
已修复，请使用最新的SDK和插件

**Comment by lipeng219901** [comment]
这个plugin 怎么添加到sdk 编出来 jar包 里面呢。源代码文件夹直接拷贝进去吗，调用规则呢

**Comment by wangzhzh** [comment]
请参考官方集成文档
