### ISSUE TITLE
 影响dataBinging,databinding编译出来的apk启动崩溃

### ISSUE THREAD

**Issue by liuchen8899** [sensorsdata/sa-sdk-android-plugin2#24]
java.lang.ClassNotFoundException: androidx.databinding.DataBinderMapperImpl

**Comment by yongjie520** [comment]
我也遇到同样的问题，使用DataBinding的时候会出现

**Comment by yongjie520** [comment]
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/databinding/DataBinderMapperImpl;        at androidx.databinding.DataBindingUtil.<clinit>(DataBindingUtil.java:32)        at androidx.databinding.DataBindingUtil.getDefaultComponent(DataBindingUtil.java:65)
at androidx.databinding.DataBindingUtil.getDefaultComponent(DataBindingUtil.java:65)        at com.xxxxxxxx.XXXXBinding.inflate(ActivityV2MainBinding.java:42)
