### ISSUE TITLE
java.nio.file.FileSystemException

### ISSUE THREAD

**Issue by hlz217057** [sensorsdata/sa-sdk-android-plugin2#34]
at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:278)
	at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110)
	at java.base/java.nio.file.Files.deleteIfExists(Files.java:1181)
	at com.android.utils.PathUtils.deleteRecursivelyIfExists(PathUtils.java:91)
	at com.android.utils.FileUtils.deleteRecursivelyIfExists(FileUtils.java:304)
	at com.android.utils.FileUtils.deletePath(FileUtils.java:64)
	at com.android.build.gradle.internal.tasks.NonIncrementalTaskKt.cleanUpTaskOutputs(NonIncrementalTask.kt:89)
	at com.android.build.gradle.internal.tasks.NonIncrementalTask$taskAction$$inlined$recordTaskAction$1.invoke(BaseTask.kt:65)
	at com.android.build.gradle.internal.tasks.Blocks.recordSpan(Blocks.java:51)
	at com.android.build.gradle.internal.tasks.NonIncrementalTask.taskAction(NonIncrementalTask.kt:97)
	at jdk.internal.reflect.GeneratedMethodAccessor1627.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:125)
	... 116 more

**Comment by GvcZhang** [comment]
嗨，请提供一个完整的日志。在编译的时候可以添加 --stacktrace 选项，用于输出详细的日志信息。
