### ISSUE TITLE
关于插件默认对React Native工程添加埋点的问题

### ISSUE THREAD

**Issue by tianjyan** [sensorsdata/sa-sdk-android-plugin2#36]
Hi Team，我的工程结构是Android 原生+React Native的组合，对于神策的SDK，我只集成了Android的SDK，但是并没有集成React Native的SDK。最近我这边在进行升级AGP 8的相关工作，在升级Plugin到4.0的版本以后，进入React Native的工程会提示如下错误：

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/sensorsdata/analytics/RNAgent;
	at com.facebook.react.views.view.ReactClippingViewManager.addView(ReactClippingViewManager.java:19)
	at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:533)
	at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:217)
	at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:915)
	at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1026)
	at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1086)
	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
```

我查看了你们工程的相关代码，发现在4.0的版本以后，会默认添加对RN的处理：

[if (handleRN())](https://github.com/sensorsdata/sa-sdk-android-plugin2/blob/8c951e1fd0245339b73bdaa118a302a4e2c24625/sa-gradle-plugin/src/main/kotlin/com/sensorsdata/analytics/android/plugin/viewclick/SensorsAutoTrackMethodVisitor.kt#L463)
[private fun handleRN(): Boolean](https://github.com/sensorsdata/sa-sdk-android-plugin2/blob/8c951e1fd0245339b73bdaa118a302a4e2c24625/sa-gradle-plugin/src/main/kotlin/com/sensorsdata/analytics/android/plugin/viewclick/SensorsAutoTrackMethodVisitor.kt#L736)'

想问下是否可以通过添加一个plugin的设置选项来屏蔽这个设置？

**Comment by tianjyan** [comment]
4.0.2已经支持，关闭这个问题
